{
  "openapi": "3.0",
  "info": {
    "title": "版本管理系统",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "登录"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "summary": "50-1登录",
        "x-apifox-folder": "登录",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "",
        "tags": [
          "登录"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJndWxsLXVzZXIiLCJpYXQiOjE2NjYwNTk0NjYsImV4cCI6MTY2NjE0NTg2NiwidWlkIjoiYWRtaW4ifQ.rnwAHxpqiLtU0fFsO50tSOq1P3kIVDNND1Kq0ywn6-g",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "uid": {
                    "type": "string",
                    "description": "账号"
                  },
                  "password": {
                    "type": "string",
                    "title": "",
                    "description": "密码"
                  },
                  "interfaceNum": {
                    "type": "string",
                    "description": "50-1",
                    "title": ""
                  }
                },
                "x-apifox-orders": [
                  "uid",
                  "password",
                  "interfaceNum"
                ],
                "required": [
                  "uid",
                  "password",
                  "interfaceNum"
                ],
                "x-apifox-ignore-properties": []
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/%E7%99%BB%E5%BD%95",
                  "x-apifox-overrides": {}
                },
                "examples": {
                  "1": {
                    "summary": "成功示例 ",
                    "value": {
                      "user": {
                        "id": 1,
                        "uid": "admin",
                        "name": "admin",
                        "phone": "1",
                        "info": "1"
                      },
                      "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJndWxsLXVzZXIiLCJpYXQiOjE2NjU2NDA0ODIsImV4cCI6MTY2NTcyNjg4MiwidWlkIjoiYWRtaW4ifQ.UFrDz9XxodJ3W3f05ATu93NcVrALgF3osqyb6Q4HNmQ"
                    }
                  },
                  "2": {
                    "summary": "成功示例 ",
                    "value": {
                      "user": {
                        "id": 1,
                        "uid": "admin",
                        "name": "admin",
                        "phone": "1",
                        "info": "1"
                      },
                      "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJndWxsLXVzZXIiLCJpYXQiOjE2NjU2NDA0ODIsImV4cCI6MTY2NTcyNjg4MiwidWlkIjoiYWRtaW4ifQ.UFrDz9XxodJ3W3f05ATu93NcVrALgF3osqyb6Q4HNmQ"
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox'": "https://www.apifox.cn/web/project/1649814/apis/api-40809335-run"
      }
    },
    "/logout": {
      "get": {
        "summary": "50-4退出",
        "x-apifox-folder": "登录",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "",
        "tags": [
          "登录"
        ],
        "parameters": [
          {
            "name": "interfaceNum",
            "in": "query",
            "description": "",
            "required": false,
            "example": "50-4",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJndWxsLXVzZXIiLCJpYXQiOjE2NjYwNTk0NjYsImV4cCI6MTY2NjE0NTg2NiwidWlkIjoiYWRtaW4ifQ.rnwAHxpqiLtU0fFsO50tSOq1P3kIVDNND1Kq0ywn6-g",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-ignore-properties": [],
                  "x-apifox-orders": []
                }
              }
            }
          }
        },
        "x-run-in-apifox'": "https://www.apifox.cn/web/project/1649814/apis/api-40820393-run"
      }
    },
    "/user/getMenuList": {
      "get": {
        "summary": "50-2获取菜单",
        "x-apifox-folder": "登录",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "",
        "tags": [
          "登录"
        ],
        "parameters": [
          {
            "name": "interfaceNum",
            "in": "query",
            "description": "",
            "required": false,
            "example": "50-2",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJndWxsLXVzZXIiLCJpYXQiOjE2NjYwNTk0NjYsImV4cCI6MTY2NjE0NTg2NiwidWlkIjoiYWRtaW4ifQ.rnwAHxpqiLtU0fFsO50tSOq1P3kIVDNND1Kq0ywn6-g",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "role": {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "description": "角色"
                      }
                    },
                    "menu": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer",
                            "description": "id"
                          },
                          "name": {
                            "type": "string",
                            "title": "",
                            "description": "菜单名"
                          },
                          "path": {
                            "type": "string",
                            "title": "",
                            "description": "菜单路径"
                          },
                          "isMenu": {
                            "type": "integer",
                            "title": "",
                            "description": "是否是菜单"
                          },
                          "pid": {
                            "type": "integer",
                            "title": "",
                            "description": "父菜单权限"
                          },
                          "write": {
                            "type": "boolean",
                            "title": "",
                            "description": "读写"
                          }
                        },
                        "required": [
                          "id",
                          "name",
                          "path",
                          "isMenu",
                          "pid",
                          "write"
                        ],
                        "x-apifox-orders": [
                          "id",
                          "name",
                          "path",
                          "isMenu",
                          "pid",
                          "write"
                        ],
                        "x-apifox-ignore-properties": []
                      }
                    }
                  },
                  "required": [
                    "role",
                    "menu"
                  ],
                  "x-apifox-orders": [
                    "role",
                    "menu"
                  ],
                  "x-apifox-ignore-properties": []
                },
                "examples": {
                  "1": {
                    "summary": "成功示例 ",
                    "value": {
                      "role": [
                        "管理员"
                      ],
                      "menu": [
                        {
                          "id": 23,
                          "name": "周低大",
                          "code": "25",
                          "path": "/",
                          "isMenu": 1,
                          "child": [
                            {
                              "id": 30,
                              "name": "周低大11",
                              "code": "2000",
                              "path": "/",
                              "isMenu": 1
                            },
                            {
                              "id": 31,
                              "name": "周低大111",
                              "code": "20000",
                              "path": "/",
                              "isMenu": 1
                            },
                            {
                              "id": 36,
                              "name": "周低大111111",
                              "code": "20001000",
                              "path": "/a/aaaa1111",
                              "isMenu": 1,
                              "child": [
                                {
                                  "id": 41,
                                  "name": "周低大111111:解决问题权限",
                                  "code": "20001000:write",
                                  "path": "/",
                                  "isMenu": 0
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "id": 28,
                          "name": "周低大1",
                          "code": "200",
                          "path": "/",
                          "isMenu": 1,
                          "child": [
                            {
                              "id": 33,
                              "name": "周低大1111",
                              "code": "200000",
                              "path": "/",
                              "isMenu": 1
                            },
                            {
                              "id": 35,
                              "name": "周低大11111",
                              "code": "2000000",
                              "path": "/",
                              "isMenu": 1
                            }
                          ]
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox'": "https://www.apifox.cn/web/project/1649814/apis/api-40831960-run"
      }
    },
    "/register": {
      "post": {
        "summary": "50-3注册",
        "x-apifox-folder": "登录",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "",
        "tags": [
          "登录"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "uid": {
                    "type": "string",
                    "description": "用户名"
                  },
                  "phone": {
                    "type": "string",
                    "title": "",
                    "description": "手机号"
                  },
                  "name": {
                    "type": "string",
                    "title": "",
                    "description": "姓名"
                  },
                  "info": {
                    "type": "string",
                    "title": "",
                    "description": "个人信息"
                  },
                  "password": {
                    "type": "string",
                    "title": "",
                    "description": "密码"
                  },
                  "interfaceNum": {
                    "type": "string",
                    "description": "50-3"
                  }
                },
                "x-apifox-orders": [
                  "uid",
                  "phone",
                  "name",
                  "info",
                  "password",
                  "interfaceNum"
                ],
                "required": [
                  "uid",
                  "phone",
                  "name",
                  "password",
                  "interfaceNum"
                ],
                "x-apifox-ignore-properties": []
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-ignore-properties": [],
                  "x-apifox-orders": []
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": {
                      "messages": "注册成功"
                    }
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox'": "https://www.apifox.cn/web/project/1649814/apis/api-41062735-run"
      }
    },
    "/user/getPermissionList": {
      "get": {
        "summary": "50-5获取权限列表",
        "x-apifox-folder": "登录",
        "x-apifox-status": "released",
        "deprecated": false,
        "description": "",
        "tags": [
          "登录"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJndWxsLXVzZXIiLCJpYXQiOjE2NjYwNTk0NjYsImV4cCI6MTY2NjE0NTg2NiwidWlkIjoiYWRtaW4ifQ.rnwAHxpqiLtU0fFsO50tSOq1P3kIVDNND1Kq0ywn6-g",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer",
                        "description": "模块id"
                      },
                      "name": {
                        "type": "string",
                        "title": "",
                        "description": "模块名称"
                      },
                      "path": {
                        "type": "string",
                        "title": "",
                        "description": "path"
                      },
                      "isMenu": {
                        "type": "integer",
                        "title": "",
                        "description": "是否菜单"
                      },
                      "pid": {
                        "type": "integer",
                        "title": "",
                        "description": "父id"
                      },
                      "write": {
                        "type": "boolean",
                        "title": "",
                        "description": "是否读写"
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "path",
                      "isMenu",
                      "pid",
                      "write"
                    ],
                    "x-apifox-orders": [
                      "id",
                      "name",
                      "path",
                      "isMenu",
                      "pid",
                      "write"
                    ],
                    "x-apifox-ignore-properties": []
                  }
                },
                "examples": {
                  "1": {
                    "summary": "成功示例",
                    "value": [
                      {
                        "id": 36,
                        "name": "周低大111111",
                        "path": "/aaaaa",
                        "isMenu": 1,
                        "pid": 23,
                        "write": true
                      },
                      {
                        "id": 42,
                        "name": "华门道般油便",
                        "path": "/non",
                        "isMenu": 1,
                        "pid": 23,
                        "write": true
                      },
                      {
                        "id": 44,
                        "name": "律适取",
                        "path": "/irure",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 52,
                        "name": "律适",
                        "path": "/iruree",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 54,
                        "name": "家了器",
                        "path": "/consequatinculpanulla",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 56,
                        "name": "可快各开办深",
                        "path": "/dolorculpaDuisdolore",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 61,
                        "name": "何张办层",
                        "path": "/ullamcoculpatempor",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 63,
                        "name": "你好",
                        "path": "/admin",
                        "isMenu": 1,
                        "pid": 23,
                        "write": true
                      },
                      {
                        "id": 66,
                        "name": "史活影只山",
                        "path": "/aliquaoccaecatdolorefugiat",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 72,
                        "name": "史活影只山1",
                        "path": "/aliquaoccaecatdolorefugiaat",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 74,
                        "name": "圆目布天情义况",
                        "path": "/asdw",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 79,
                        "name": "圆目布天情义况1",
                        "path": "/asdww",
                        "isMenu": 1,
                        "pid": 28,
                        "write": true
                      },
                      {
                        "id": 95,
                        "name": "国将工米型",
                        "path": "/ass",
                        "isMenu": 1,
                        "pid": 92,
                        "write": true
                      },
                      {
                        "id": 111,
                        "name": "测试模块",
                        "path": "/ajgka",
                        "isMenu": 1,
                        "pid": 105,
                        "write": true
                      },
                      {
                        "id": 113,
                        "name": "kjkkl",
                        "path": "/kkkl",
                        "isMenu": 1,
                        "pid": 105,
                        "write": true
                      },
                      {
                        "id": 116,
                        "name": "dba",
                        "path": "/39d073ae6ddc46f8b1fc70e2f1ee29d2",
                        "isMenu": 1,
                        "pid": 115,
                        "write": true
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "x-run-in-apifox'": "https://www.apifox.cn/web/project/1649814/apis/api-42741865-run"
      }
    }
  },
  "components": {
    "schemas": {
      "登录": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "uid": {
                "type": "string",
                "description": "用户账号"
              },
              "name": {
                "type": "string",
                "title": "",
                "description": "名称"
              },
              "phone": {
                "type": "string",
                "title": "",
                "description": "手机号"
              },
              "info": {
                "type": "string",
                "title": "",
                "description": "个人信息"
              }
            },
            "required": [
              "id",
              "uid",
              "name",
              "phone",
              "info"
            ],
            "x-apifox-orders": [
              "id",
              "uid",
              "name",
              "phone",
              "info"
            ],
            "title": "用户名",
            "description": "说明",
            "x-apifox-ignore-properties": []
          },
          "token": {
            "type": "string"
          }
        },
        "required": [
          "user",
          "token"
        ],
        "x-apifox-orders": [
          "user",
          "token"
        ],
        "x-apifox-ignore-properties": [],
        "x-apifox-folder": ""
      }
    }
  },
  "servers": []
}